"""DevOps/cloud/SRE terminology corrections dictionary.

Maps a canonical term to the list of ways Whisper is likely to mis-transcribe it
(itself included, plus hyphen-broken syllables and known phonetic near-misses).
Consumed by devops_transcription.py's correction pipeline (phrase/word/fuzzy
matching) and by vocabulary_learning.py's near-miss detection.

Extracted out of devops_transcription.py and substantially expanded (from ~60
canonical terms to several hundred) as part of Phase 4 (see REPOSITORY_AUDIT.md).
This is the static, hand-curated foundation; glossary.py's glossary.json layer on
top of this is the persistent, human-approved, self-growing layer (see
vocabulary_learning.py) — both feed the same correction pipeline.
"""

DEVOPS_VOCABULARY = {
    # ------------------------------------------------------------------
    # Containers & orchestration
    # ------------------------------------------------------------------
    "kubernetes": ["kubernetes", "k8s", "k-8-s", "qbritis", "cubernetes", "cubernetis"],
    "docker": ["docker", "dock-er", "dockers"],
    "podman": ["podman", "pod-man"],
    "containerd": ["containerd", "container-d", "container dee"],
    "cri-o": ["cri-o", "crio", "c-r-i-o"],
    "pod": ["pod", "pods"],
    "node": ["node", "nodes"],
    "cluster": ["cluster", "clus-ter"],
    "namespace": ["namespace", "name-space"],
    "deployment": ["deployment", "de-ploy-ment", "deploy-mint"],
    "replicaset": ["replicaset", "replica set", "rep-li-ca-set"],
    "statefulset": ["statefulset", "stateful set", "state-ful-set"],
    "daemonset": ["daemonset", "daemon set", "day-mon-set"],
    "service": ["service", "ser-vis"],
    "ingress": ["ingress", "in-gress"],
    "configmap": ["configmap", "config map", "con-fig-map"],
    "secret": ["secret", "secrets", "seekers"],
    "persistent volume": ["persistent volume", "pv", "per-sis-tent volume"],
    "persistent volume claim": ["persistent volume claim", "pvc", "p-v-c"],
    "horizontal pod autoscaler": ["horizontal pod autoscaler", "hpa", "h-p-a"],
    "custom resource definition": ["custom resource definition", "crd", "c-r-d"],
    "kubelet": ["kubelet", "cube-let"],
    "kube-proxy": ["kube-proxy", "cube proxy", "kube proxy"],
    "etcd": ["etcd", "et-c-d", "etsy-d"],
    "helm": ["helm", "helm chart"],
    "cgroup": ["cgroup", "c-group", "control group"],
    "microservices": ["microservices", "micro-services", "micro services"],
    "container": ["container", "con-tain-er"],
    "container registry": ["container registry", "con-tain-er registry"],
    "container image": ["container image", "docker image"],

    # ------------------------------------------------------------------
    # Cloud providers (general)
    # ------------------------------------------------------------------
    "aws": ["aws", "a-w-s", "a w s", "amazon web services"],
    "gcp": ["gcp", "google cloud platform", "g-c-p", "google cloud"],
    "azure": ["azure", "az-ur", "microsoft azure"],

    # ------------------------------------------------------------------
    # AWS services
    # ------------------------------------------------------------------
    "ec2": ["ec2", "e-c-2", "e c 2", "elastic compute cloud"],
    "s3": ["s3", "s-3", "s three", "simple storage service"],
    "rds": ["rds", "r-d-s", "relational database service"],
    "lambda": ["lambda", "lam-da", "aws lambda"],
    "ecs": ["ecs", "e-c-s", "elastic container service"],
    "eks": ["eks", "e-k-s", "elastic kubernetes service"],
    "fargate": ["fargate", "far-gate"],
    "cloudfront": ["cloudfront", "cloud front", "cloud-front"],
    "route53": ["route53", "route 53", "route fifty three"],
    "iam": ["iam", "i-a-m", "identity and access management"],
    "vpc": ["vpc", "v-p-c", "virtual private cloud"],
    "cloudwatch": ["cloudwatch", "cloud watch", "cloud-watch"],
    "sqs": ["sqs", "s-q-s", "simple queue service"],
    "sns": ["sns", "s-n-s", "simple notification service"],
    "dynamodb": ["dynamodb", "dynamo db", "dynamo-db"],
    "elasticache": ["elasticache", "elastic cache", "elastic-cache"],
    "ecr": ["ecr", "e-c-r", "elastic container registry"],
    "codepipeline": ["codepipeline", "code pipeline"],
    "codebuild": ["codebuild", "code build"],
    "codedeploy": ["codedeploy", "code deploy"],
    "cloudformation": ["cloudformation", "cloud formation", "cloud-formation"],
    "auto scaling group": ["auto scaling group", "asg", "a-s-g"],
    "application load balancer": ["application load balancer", "alb", "a-l-b"],
    "network load balancer": ["network load balancer", "nlb", "n-l-b"],
    "ebs": ["ebs", "e-b-s", "elastic block store"],
    "efs": ["efs", "e-f-s", "elastic file system"],
    "glacier": ["glacier", "s3 glacier"],
    "kinesis": ["kinesis", "kin-e-sis"],
    "athena": ["athena", "a-thee-na"],
    "redshift": ["redshift", "red shift", "red-shift"],
    "aurora": ["aurora", "aws aurora"],
    "secrets manager": ["secrets manager", "aws secrets manager"],
    "systems manager": ["systems manager", "ssm", "s-s-m"],
    "kms": ["kms", "k-m-s", "key management service"],
    "waf": ["waf", "w-a-f", "web application firewall"],
    "aws shield": ["aws shield", "shield"],
    "aws organizations": ["aws organizations", "organizations"],
    "sts": ["sts", "s-t-s", "security token service"],
    "cloudtrail": ["cloudtrail", "cloud trail"],
    "elastic beanstalk": ["elastic beanstalk", "beanstalk"],
    "step functions": ["step functions", "aws step functions"],
    "eventbridge": ["eventbridge", "event bridge"],

    # ------------------------------------------------------------------
    # Azure services
    # ------------------------------------------------------------------
    "azure devops": ["azure devops", "azure dev ops"],
    "aks": ["aks", "a-k-s", "azure kubernetes service"],
    "azure functions": ["azure functions", "azure function"],
    "blob storage": ["blob storage", "azure blob storage", "blob-storage"],
    "azure sql": ["azure sql", "azure sequel"],
    "azure monitor": ["azure monitor"],
    "azure active directory": ["azure active directory", "azure ad", "entra id"],
    "arm template": ["arm template", "azure resource manager template"],
    "azure pipelines": ["azure pipelines"],
    "cosmos db": ["cosmos db", "cosmosdb", "azure cosmos db"],
    "azure key vault": ["azure key vault", "key vault"],
    "application gateway": ["application gateway", "app gateway"],
    "vnet": ["vnet", "v-net", "virtual network"],

    # ------------------------------------------------------------------
    # GCP services
    # ------------------------------------------------------------------
    "gke": ["gke", "g-k-e", "google kubernetes engine"],
    "cloud run": ["cloud run", "gcp cloud run"],
    "cloud functions": ["cloud functions", "gcp cloud functions"],
    "cloud storage": ["cloud storage", "gcs", "google cloud storage"],
    "bigquery": ["bigquery", "big query"],
    "cloud sql": ["cloud sql", "gcp cloud sql"],
    "pub/sub": ["pub/sub", "pub sub", "pubsub"],
    "cloud build": ["cloud build", "gcp cloud build"],
    "firestore": ["firestore", "fire store"],
    "cloud spanner": ["cloud spanner", "spanner"],

    # ------------------------------------------------------------------
    # CI/CD tools
    # ------------------------------------------------------------------
    "jenkins": ["jenkins", "jen-kins"],
    "gitlab": ["gitlab", "git-lab", "git labs"],
    "gitlab ci": ["gitlab ci", "gitlab c-i", "csed pipeline"],
    "github": ["github", "git-hub", "git hubs"],
    "github actions": ["github actions", "git hub actions"],
    "circleci": ["circleci", "circle ci", "circle c-i"],
    "travis ci": ["travis ci", "travis c-i"],
    "teamcity": ["teamcity", "team city"],
    "bamboo": ["bamboo", "bam-boo"],
    "argocd": ["argocd", "argo cd", "argos cd", "argo c-d"],
    "flux": ["flux", "fluxcd", "flux cd"],
    "spinnaker": ["spinnaker", "spin-a-ker"],
    "tekton": ["tekton", "tek-ton"],
    "drone ci": ["drone ci", "drone c-i"],
    "ci/cd": ["ci/cd", "ci cd", "c-i c-d", "csed"],
    "ci/cd pipeline": ["ci/cd pipeline", "csed pipeline", "csed pipelines"],

    # ------------------------------------------------------------------
    # Infrastructure as Code
    # ------------------------------------------------------------------
    "terraform": ["terraform", "terra-form", "terr-form", "teleform"],
    "terragrunt": ["terragrunt", "terra grunt"],
    "pulumi": ["pulumi", "pu-lu-mi"],
    "ansible": ["ansible", "ans-able", "ansi-bull"],
    "chef": ["chef", "chef infra"],
    "puppet": ["puppet", "pup-pet"],
    "saltstack": ["saltstack", "salt stack"],
    "packer": ["packer", "pack-er"],
    "infrastructure as code": ["infrastructure as code", "iac", "i-a-c", "infrastructure as cold"],
    "gitops": ["gitops", "git ops", "git-ops"],

    # ------------------------------------------------------------------
    # Observability / monitoring / logging
    # ------------------------------------------------------------------
    "prometheus": ["prometheus", "prom-eth-eus"],
    "grafana": ["grafana", "gra-fan-a"],
    "datadog": ["datadog", "data-dog"],
    "new relic": ["new relic", "new-relic"],
    "splunk": ["splunk", "split-bank"],
    "elasticsearch": ["elasticsearch", "elastic-search"],
    "logstash": ["logstash", "log-stash"],
    "kibana": ["kibana", "ki-ba-na"],
    "elk stack": ["elk stack", "e-l-k stack"],
    "opentelemetry": ["opentelemetry", "open telemetry", "open-telemetry"],
    "jaeger": ["jaeger", "yay-ger", "jay-ger"],
    "zipkin": ["zipkin", "zip-kin"],
    "loki": ["loki", "low-key"],
    "pagerduty": ["pagerduty", "pager duty", "pager-duty"],
    "opsgenie": ["opsgenie", "ops genie", "ops-genie"],
    "victorops": ["victorops", "victor ops"],
    "sentry": ["sentry", "sen-tree"],
    "monitoring": ["monitoring", "moni-tor-ing"],
    "logging": ["logging", "log-ging"],
    "metrics": ["metrics", "met-riks"],
    "alerting": ["alerting", "alert routing"],
    "dashboard": ["dashboard", "dash-board"],
    "observability": ["observability", "obser-va-bility"],

    # ------------------------------------------------------------------
    # Messaging / streaming
    # ------------------------------------------------------------------
    "kafka": ["kafka", "coffee for a", "caf-ka"],
    "rabbitmq": ["rabbitmq", "rabbit m-q", "rabbit mq"],
    "nats": ["nats", "n-a-t-s"],
    "activemq": ["activemq", "active m-q", "active mq"],
    "zeromq": ["zeromq", "zero m-q", "zero mq"],
    "pulsar": ["pulsar", "pul-sar", "apache pulsar"],
    "message queue": ["message queue", "message-queue"],
    "event stream": ["event stream", "event streaming"],

    # ------------------------------------------------------------------
    # Databases & storage
    # ------------------------------------------------------------------
    "database": ["database", "data-base"],
    "postgresql": ["postgresql", "postgres", "post-gre-sql", "postgres sql"],
    "mysql": ["mysql", "my sql", "my-sequel"],
    "mongodb": ["mongodb", "mongo-db", "mongo db"],
    "redis": ["redis", "red-is"],
    "cassandra": ["cassandra", "cas-san-dra"],
    "cockroachdb": ["cockroachdb", "cockroach db"],
    "mariadb": ["mariadb", "maria db"],
    "oracle db": ["oracle db", "oracle database"],
    "sql server": ["sql server", "sequel server"],
    "neo4j": ["neo4j", "neo four j"],
    "influxdb": ["influxdb", "influx db"],
    "timescaledb": ["timescaledb", "timescale db"],

    # ------------------------------------------------------------------
    # Service mesh & networking
    # ------------------------------------------------------------------
    "istio": ["istio", "iss-tee-oh"],
    "linkerd": ["linkerd", "link-erd", "linker-d"],
    "envoy": ["envoy", "en-voy"],
    "consul": ["consul", "con-sul"],
    "nginx": ["nginx", "engine-x", "en-jin-x"],
    "haproxy": ["haproxy", "h-a proxy", "ha proxy"],
    "traefik": ["traefik", "trae-fik", "traffic"],
    "coredns": ["coredns", "core d-n-s", "core dns"],
    "load balancer": ["load balancer", "load-balancer", "load traffic"],
    "reverse proxy": ["reverse proxy", "reverse-proxy"],
    "cdn": ["cdn", "c-d-n", "content delivery network"],
    "dns": ["dns", "d-n-s"],
    "vpn": ["vpn", "v-p-n"],
    "subnet": ["subnet", "sub-net"],
    "cidr": ["cidr", "cider", "c-i-d-r"],
    "firewall": ["firewall", "fire-wall"],

    # ------------------------------------------------------------------
    # Security
    # ------------------------------------------------------------------
    "vault": ["vault", "hashicorp vault"],
    "trivy": ["trivy", "trevi", "triv-y"],
    "sonarqube": ["sonarqube", "sonar qube", "sonar cube"],
    "snyk": ["snyk", "sneek"],
    "owasp": ["owasp", "oh-wasp"],
    "veracode": ["veracode", "vera code"],
    "aqua security": ["aqua security", "aqua sec"],
    "falco": ["falco", "fal-co"],
    "cert-manager": ["cert-manager", "cert manager", "certificate manager"],
    "tls": ["tls", "t-l-s", "transport layer security"],
    "ssl": ["ssl", "s-s-l"],
    "oauth": ["oauth", "o-auth"],
    "saml": ["saml", "sam-el"],
    "jwt": ["jwt", "j-w-t", "jay-w-t", "json web token"],
    "rbac": ["rbac", "r-b-a-c", "role based access control"],
    "mfa": ["mfa", "m-f-a", "multi factor authentication"],
    "siem": ["siem", "sim", "security information and event management"],
    "secret management": ["secret management", "secrets management"],

    # ------------------------------------------------------------------
    # Version control & collaboration
    # ------------------------------------------------------------------
    "git": ["git", "git version control"],
    "bitbucket": ["bitbucket", "bit-bucket"],
    "jira": ["jira", "jee-ra"],
    "confluence": ["confluence", "con-flu-ence"],
    "slack": ["slack", "slack channel"],
    "microsoft teams": ["microsoft teams", "ms teams", "teams"],

    # ------------------------------------------------------------------
    # Runtimes / languages / package managers
    # ------------------------------------------------------------------
    "nodejs": ["nodejs", "node js", "node dot js"],
    "npm": ["npm", "n-p-m"],
    "pip": ["pip", "python pip"],
    "maven": ["maven", "may-ven"],
    "gradle": ["gradle", "grad-el"],
    "jvm": ["jvm", "j-v-m", "java virtual machine"],
    "dotnet": ["dotnet", "dot net", ".net"],
    "fastapi": ["fastapi", "fast api", "fast a-p-i"],

    # ------------------------------------------------------------------
    # DevOps / SRE concepts & processes
    # ------------------------------------------------------------------
    "devops": ["devops", "dev-ops", "dev ops"],
    "sre": ["sre", "s-r-e", "site reliability engineer"],
    "incident": ["incident", "in-ci-dent"],
    "incident response": ["incident response", "incident-response"],
    "postmortem": ["postmortem", "post-mortem", "post mortem"],
    "runbook": ["runbook", "run-book"],
    "on-call": ["on-call", "on call", "oncall"],
    "escalation": ["escalation", "es-cal-ay-shun", "desklation"],
    "escalation path": ["escalation path", "asclicion path"],
    "handover": ["handover", "hand-over"],
    "disaster recovery": ["disaster recovery", "dis-as-ter re-cov-ery"],
    "high availability": ["high availability", "high a-vail-ability"],
    "auto scaling": ["auto scaling", "auto-scal-ing"],
    "horizontal scaling": ["horizontal scaling", "scale out"],
    "vertical scaling": ["vertical scaling", "scale up"],
    "load testing": ["load testing", "load-testing"],
    "feature flag": ["feature flag", "feature-flag", "feature toggle"],
    "service discovery": ["service discovery", "service-discovery"],
    "circuit breaker": ["circuit breaker", "circuit-breaker"],
    "rate limiting": ["rate limiting", "rate-limiting"],
    "api gateway": ["api gateway", "a-p-i gateway"],
    "webhook": ["webhook", "web-hook"],
    "cron job": ["cron job", "cron-job", "cronjob"],
    "blue-green deployment": ["blue-green deployment", "blue green deployment"],
    "canary deployment": ["canary deployment", "canary release"],
    "rolling update": ["rolling update", "rolling-update"],
    "immutable infrastructure": ["immutable infrastructure"],
    "chaos engineering": ["chaos engineering", "chaos-engineering"],
    "sli": ["sli", "s-l-i", "service level indicator"],
    "slo": ["slo", "s-l-o", "service level objective"],
    "sla": ["sla", "s-l-a", "service level agreement"],
    "rto": ["rto", "r-t-o", "recovery time objective"],
    "rpo": ["rpo", "r-p-o", "recovery point objective"],
    "pipeline": ["pipeline", "pipe-line"],
    "orchestration": ["orchestration", "pay-bin orchestration"],
    "provisioning": ["provisioning", "pro-vision-ing"],
    "validation": ["validation", "valid-ation"],
    "environment": ["environment", "en-vi-ron-ment"],
    "staging": ["staging", "stage-ing"],
    "production": ["production", "pro-duc-tion"],
    "configuration": ["configuration", "config", "con-fig"],
    "environment variables": ["environment variables", "android variables", "and-red variables"],
    "uptime": ["uptime", "up-time"],
    "downtime": ["downtime", "down-time"],
    "latency": ["latency", "la-ten-cy"],
    "throughput": ["throughput", "through-put"],
    "availability": ["availability", "avail-ability"],
    "scalability": ["scalability", "scal-ability"],
    "reliability": ["reliability", "re-lie-ability"],
    "failover": ["failover", "fail-over", "fail over"],
    "rollback": ["rollback", "roll-back", "roll back"],
    "infrastructure": ["infrastructure", "infra-structure"],
    "restart": ["restart", "re-start"],
    "scaling": ["scaling", "scal-ing"],
    "traffic": ["traffic", "traf-fic"],
    "spike": ["spike", "spik", "flash"],
    "peak": ["peak", "peek"],
    "idle": ["idle", "eye-dul"],
    "graceful": ["graceful", "grace-ful"],
    "shutdown": ["shutdown", "shut-down"],
    "startup": ["startup", "start-up"],
    "best practices": ["best practices", "best prac-ti-ces"],
    "load balancing": ["load balancing", "load-bal-an-cing"],
    "version control": ["version control", "ver-shun con-trol"],

    # ------------------------------------------------------------------
    # AWS services — round 2
    # ------------------------------------------------------------------
    "aws batch": ["aws batch", "batch"],
    "aws glue": ["aws glue", "glue"],
    "aws appsync": ["aws appsync", "appsync"],
    "amplify": ["amplify", "aws amplify"],
    "cognito": ["cognito", "aws cognito"],
    "aws x-ray": ["aws x-ray", "x-ray", "x ray"],
    "cloudsearch": ["cloudsearch", "cloud search"],
    "neptune": ["neptune", "amazon neptune"],
    "documentdb": ["documentdb", "document db"],
    "msk": ["msk", "m-s-k", "managed streaming for kafka"],
    "amazon mq": ["amazon mq", "amazon m-q"],
    "transit gateway": ["transit gateway", "tgw"],
    "direct connect": ["direct connect", "aws direct connect"],
    "privatelink": ["privatelink", "private link"],
    "nat gateway": ["nat gateway", "n-a-t gateway"],
    "internet gateway": ["internet gateway", "i-g-w"],
    "elastic ip": ["elastic ip", "e-i-p"],
    "aws backup": ["aws backup"],
    "aws config": ["aws config"],
    "trusted advisor": ["trusted advisor"],
    "well-architected framework": ["well-architected framework", "well architected framework"],
    "control tower": ["control tower", "aws control tower"],
    "service catalog": ["service catalog", "aws service catalog"],
    "cost explorer": ["cost explorer", "aws cost explorer"],
    "savings plans": ["savings plans"],
    "reserved instances": ["reserved instances", "r-i-s"],
    "spot instances": ["spot instances"],
    "acm": ["acm", "a-c-m", "certificate manager"],
    "ses": ["ses", "s-e-s", "simple email service"],
    "sagemaker": ["sagemaker", "sage maker"],
    "textract": ["textract"],
    "rekognition": ["rekognition"],

    # ------------------------------------------------------------------
    # Azure services — round 2
    # ------------------------------------------------------------------
    "azure app service": ["azure app service", "app service"],
    "azure container instances": ["azure container instances", "aci"],
    "azure container registry": ["azure container registry", "acr"],
    "azure service bus": ["azure service bus", "service bus"],
    "azure event hubs": ["azure event hubs", "event hubs"],
    "azure data factory": ["azure data factory", "data factory"],
    "azure synapse": ["azure synapse", "synapse analytics"],
    "azure databricks": ["azure databricks"],
    "azure log analytics": ["azure log analytics", "log analytics"],
    "azure sentinel": ["azure sentinel", "sentinel"],
    "azure bastion": ["azure bastion", "bastion"],
    "azure front door": ["azure front door", "front door"],
    "azure traffic manager": ["azure traffic manager", "traffic manager"],
    "azure arc": ["azure arc"],
    "azure policy": ["azure policy"],

    # ------------------------------------------------------------------
    # GCP services — round 2
    # ------------------------------------------------------------------
    "cloud dataflow": ["cloud dataflow", "dataflow"],
    "cloud dataproc": ["cloud dataproc", "dataproc"],
    "cloud composer": ["cloud composer", "composer"],
    "cloud endpoints": ["cloud endpoints"],
    "cloud armor": ["cloud armor"],
    "cloud cdn": ["cloud cdn"],
    "cloud interconnect": ["cloud interconnect"],
    "cloud nat": ["cloud nat"],
    "stackdriver": ["stackdriver", "google cloud monitoring"],
    "anthos": ["anthos"],
    "cloud tasks": ["cloud tasks"],
    "cloud scheduler": ["cloud scheduler"],

    # ------------------------------------------------------------------
    # Kubernetes ecosystem — round 2
    # ------------------------------------------------------------------
    "kubectl": ["kubectl", "cube control", "cube c-t-l"],
    "kustomize": ["kustomize", "customize"],
    "rancher": ["rancher", "ran-cher"],
    "openshift": ["openshift", "open shift"],
    "k3s": ["k3s", "k-3-s"],
    "kind": ["kind", "kubernetes in docker"],
    "minikube": ["minikube", "mini kube"],
    "kops": ["kops", "k-ops"],
    "eksctl": ["eksctl", "e-k-s c-t-l"],
    "velero": ["velero", "vel-air-oh"],
    "longhorn": ["longhorn", "long horn"],
    "metallb": ["metallb", "metal l-b"],
    "cluster autoscaler": ["cluster autoscaler", "cluster auto-scaler"],
    "vertical pod autoscaler": ["vertical pod autoscaler", "v-p-a"],
    "pod disruption budget": ["pod disruption budget", "p-d-b"],
    "network policy": ["network policy"],
    "admission controller": ["admission controller"],
    "operator pattern": ["operator pattern", "kubernetes operator"],
    "kubeadm": ["kubeadm", "cube adm"],
    "cilium": ["cilium", "sill-ee-um"],
    "calico": ["calico", "ca-lee-co"],
    "flannel": ["flannel", "flan-el"],

    # ------------------------------------------------------------------
    # CI/CD & IaC — round 2
    # ------------------------------------------------------------------
    "buildkite": ["buildkite", "build kite"],
    "semaphore ci": ["semaphore ci", "semaphore c-i"],
    "codefresh": ["codefresh", "code fresh"],
    "harness": ["harness", "harness io"],
    "octopus deploy": ["octopus deploy", "octopus"],
    "skaffold": ["skaffold", "scaffold"],
    "kaniko": ["kaniko", "ka-nee-ko"],
    "buildpacks": ["buildpacks", "build packs"],
    "crossplane": ["crossplane", "cross plane"],
    "aws cdk": ["aws cdk", "cloud development kit"],
    "cdktf": ["cdktf", "c-d-k-t-f", "cdk for terraform"],
    "terratest": ["terratest", "terra test"],
    "atlantis": ["atlantis", "terraform atlantis"],

    # ------------------------------------------------------------------
    # Observability — round 2
    # ------------------------------------------------------------------
    "thanos": ["thanos", "than-os"],
    "cortex": ["cortex", "cortex metrics"],
    "victoriametrics": ["victoriametrics", "victoria metrics"],
    "statsd": ["statsd", "stats d"],
    "telegraf": ["telegraf", "tele-graf"],
    "appdynamics": ["appdynamics", "app dynamics"],
    "dynatrace": ["dynatrace", "dyna-trace"],
    "honeycomb": ["honeycomb", "honey comb"],
    "lightstep": ["lightstep", "light step"],
    "grafana tempo": ["grafana tempo", "tempo"],
    "fluentd": ["fluentd", "fluent d"],
    "fluent bit": ["fluent bit"],
    "filebeat": ["filebeat", "file beat"],
    "metricbeat": ["metricbeat", "metric beat"],
    "distributed tracing": ["distributed tracing", "dist-trib-uted tracing"],
    "structured logging": ["structured logging"],
    "log aggregation": ["log aggregation"],
    "synthetic monitoring": ["synthetic monitoring"],
    "real user monitoring": ["real user monitoring", "r-u-m"],
    "apm": ["apm", "a-p-m", "application performance monitoring"],

    # ------------------------------------------------------------------
    # Databases — round 2
    # ------------------------------------------------------------------
    "snowflake": ["snowflake", "snow flake"],
    "databricks": ["databricks", "data bricks"],
    "presto": ["presto", "pres-toh"],
    "trino": ["trino", "tree-no"],
    "clickhouse": ["clickhouse", "click house"],
    "scylladb": ["scylladb", "scylla db"],
    "couchbase": ["couchbase", "couch base"],
    "couchdb": ["couchdb", "couch db"],
    "sqlite": ["sqlite", "sequel lite"],
    "vitess": ["vitess", "vy-tess"],
    "tidb": ["tidb", "t-i-d-b"],
    "yugabytedb": ["yugabytedb", "yuga byte db"],
    "memcached": ["memcached", "mem cache d"],
    "hazelcast": ["hazelcast", "hazel cast"],

    # ------------------------------------------------------------------
    # Security — round 2
    # ------------------------------------------------------------------
    "teleport": ["teleport", "tele-port"],
    "keycloak": ["keycloak", "key cloak"],
    "okta": ["okta", "ok-ta"],
    "auth0": ["auth0", "auth zero"],
    "crowdstrike": ["crowdstrike", "crowd strike"],
    "wiz": ["wiz", "wizz"],
    "prisma cloud": ["prisma cloud"],
    "qualys": ["qualys", "quality s"],
    "nessus": ["nessus", "ness-us"],
    "nmap": ["nmap", "n-map"],
    "wireshark": ["wireshark", "wire shark"],
    "fail2ban": ["fail2ban", "fail two ban"],
    "apparmor": ["apparmor", "app armor"],
    "selinux": ["selinux", "s-e-linux"],
    "open policy agent": ["open policy agent", "o-p-a"],
    "kyverno": ["kyverno", "ky-ver-no"],
    "guardduty": ["guardduty", "guard duty"],
    "security hub": ["security hub", "aws security hub"],
    "aws inspector": ["aws inspector", "inspector"],
    "amazon macie": ["amazon macie", "macie"],

    # ------------------------------------------------------------------
    # Networking — round 2
    # ------------------------------------------------------------------
    "bgp": ["bgp", "b-g-p", "border gateway protocol"],
    "ipsec": ["ipsec", "i-p-sec"],
    "wireguard": ["wireguard", "wire guard"],
    "openvpn": ["openvpn", "open v-p-n"],
    "ingress controller": ["ingress controller"],
    "kong": ["kong", "kong gateway"],
    "apigee": ["apigee", "a-p-i-gee"],

    # ------------------------------------------------------------------
    # DevOps / SRE practices & metrics — round 2
    # ------------------------------------------------------------------
    "platform engineering": ["platform engineering"],
    "internal developer platform": ["internal developer platform", "i-d-p"],
    "developer experience": ["developer experience", "dev-ex", "devex"],
    "shift left": ["shift left", "shift-left"],
    "dora metrics": ["dora metrics", "d-o-r-a metrics"],
    "mttr": ["mttr", "m-t-t-r", "mean time to recovery", "mean time to repair"],
    "mtta": ["mtta", "m-t-t-a", "mean time to acknowledge"],
    "mtbf": ["mtbf", "m-t-b-f", "mean time between failures"],
    "error budget": ["error budget"],
    "toil": ["toil"],
    "capacity planning": ["capacity planning"],
    "backpressure": ["backpressure", "back pressure"],
    "idempotency": ["idempotency", "idempotent"],
    "eventual consistency": ["eventual consistency"],
    "cap theorem": ["cap theorem"],
    "correlation id": ["correlation id", "correlation i-d"],
    "finops": ["finops", "fin-ops"],
    "resource tagging": ["resource tagging", "tagging strategy"],
    "multi-tenancy": ["multi-tenancy", "multi tenancy"],
    "zero trust": ["zero trust"],
    "least privilege": ["least privilege"],
    "defense in depth": ["defense in depth"],
    "blast radius": ["blast radius"],
    "self-healing": ["self-healing", "self healing"],
    "auto-remediation": ["auto-remediation", "auto remediation"],
    "drift detection": ["drift detection", "configuration drift"],
    "golden image": ["golden image"],
    "artifact repository": ["artifact repository", "artifact registry"],
    "package registry": ["package registry"],
    "semantic versioning": ["semantic versioning", "semver"],
    "trunk-based development": ["trunk-based development", "trunk based development"],
    "monorepo": ["monorepo", "mono repo"],
    "polyrepo": ["polyrepo", "poly repo"],
    "technical debt": ["technical debt", "tech debt"],
    "code coverage": ["code coverage"],
    "smoke test": ["smoke test"],
    "regression test": ["regression test"],
    "load test": ["load test"],
    "stress test": ["stress test"],
    "chaos monkey": ["chaos monkey"],
    "game day": ["game day"],
    "war room": ["war room"],
    "status page": ["status page"],
    "incident commander": ["incident commander"],
    "on-call rotation": ["on-call rotation", "oncall rotation"],
    "alert fatigue": ["alert fatigue"],
    "knowledge base": ["knowledge base"],
}
