#!/usr/bin/env python3
"""Write section_examples.json: labelled example statements for each KT section.

    python scripts/build_section_examples.py          # rewrite the file
    python scripts/build_section_examples.py --check  # exit 1 if it is out of date

The classifier compares a sentence with these examples as well as with the
section's title and hints (context_mapper.ContextClassifier). A section's
title and hint words alone say little: every section scored 0.45-0.60
against a sentence, so a time phrase ("for an hour", "overnight") was enough
to pull a fix or a cost note into Disaster Recovery.

The examples are the annotated facts of the golden suite's synthetic tuning
transcripts (tests/goldens), each under the first section it belongs in.
Holdouts are left out, so they still measure KTs the classifier has not
seen, and so is any transcript that is not synthetic (a customer's KT never
ships inside the product).
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GOLDEN_DIR = os.path.join(ROOT, "tests", "goldens")
OUT_PATH = os.path.join(ROOT, "section_examples.json")


def usable(golden) -> bool:
    return not golden.get("holdout") and "(synthetic)" in str(golden.get("source", ""))


def build() -> dict:
    sections = {}
    used = []
    for name in sorted(os.listdir(GOLDEN_DIR)):
        if not name.endswith(".json") or name == "baseline.json":
            continue
        with open(os.path.join(GOLDEN_DIR, name), encoding="utf-8") as fh:
            golden = json.load(fh)
        if not usable(golden):
            continue
        used.append(golden["id"])
        for fact in golden["facts"]:
            quote = " ".join(str(fact["quote"]).split())
            examples = sections.setdefault(fact["in"][0], [])
            if quote not in examples:
                examples.append(quote)
    return {
        "_about": "Generated by scripts/build_section_examples.py from the synthetic, non-holdout "
                  "goldens: " + ", ".join(used) + ". Do not edit by hand.",
        "sections": {sid: sections[sid] for sid in sorted(sections)},
    }


def render(data: dict) -> str:
    return json.dumps(data, indent=1, ensure_ascii=False) + "\n"


def main(argv) -> int:
    text = render(build())
    if "--check" in argv:
        with open(OUT_PATH, encoding="utf-8") as fh:
            if fh.read() != text:
                print("section_examples.json is out of date: run scripts/build_section_examples.py")
                return 1
        return 0
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    counts = json.loads(text)["sections"]
    print(OUT_PATH, {sid: len(v) for sid, v in counts.items()})
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
