#!/usr/bin/env python3
"""Write requirements.lock: requirements.txt plus everything it depends on,
pinned to the versions installed in this environment (P1-5).

    python scripts/lock_requirements.py

Only the dependency closure of requirements.txt is written, with
environment markers evaluated for the container (Linux, this Python
version), so packages that happen to be installed here but are not needed
(or are Windows-only) stay out of the image. Run it after changing
requirements.txt and re-run the tests before committing the new lock.
"""
import os
import re
import sys
from importlib import metadata

from packaging.markers import default_environment
from packaging.requirements import Requirement

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET_ENV = dict(default_environment(), sys_platform="linux", platform_system="Linux", os_name="posix",
                  platform_machine="x86_64")


# The image runs the CPU build of torch, which needs none of the CUDA
# runtime packages or triton that torch's Linux metadata lists for GPU wheels.
_GPU_ONLY = frozenset({"triton"})


def _canonical(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _direct_requirements():
    with open(os.path.join(ROOT, "requirements.txt"), encoding="utf-8") as fh:
        for line in fh:
            line = line.split("#", 1)[0].strip()
            if line:
                yield Requirement(line)


def closure():
    pinned, queue = {}, list(_direct_requirements())
    while queue:
        req = queue.pop()
        if req.marker and not req.marker.evaluate(dict(TARGET_ENV, extra="")):
            continue
        key = _canonical(req.name)
        if key in pinned or key in _GPU_ONLY or key.startswith(("nvidia-", "cuda-")):
            continue
        try:
            dist = metadata.distribution(req.name)
        except metadata.PackageNotFoundError:
            raise SystemExit(f"{req.name} is required but not installed here; install it, run the tests, then lock")
        # Drop a local label ("2.10.0+cpu"): the pin must read the same
        # whichever wheel index produced the environment.
        pinned[key] = (dist.metadata["Name"], dist.version.split("+", 1)[0])
        for raw in dist.requires or []:
            sub = Requirement(raw)
            extras = req.extras or {""}
            if sub.marker and not any(sub.marker.evaluate(dict(TARGET_ENV, extra=e)) for e in extras):
                continue
            queue.append(sub)
    return pinned


def main() -> int:
    pinned = closure()
    lines = ["# Generated by scripts/lock_requirements.py from requirements.txt. Do not edit by hand.",
             "# torch comes from the CPU wheel index: pip install --extra-index-url "
             "https://download.pytorch.org/whl/cpu -r requirements.lock"]
    lines += [f"{name}=={version}" for name, version in sorted(pinned.values(), key=lambda p: p[0].lower())]
    with open(os.path.join(ROOT, "requirements.lock"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"requirements.lock: {len(pinned)} packages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
